### ISSUE TITLE
Allow pasting into server, username, password fields

### ISSUE THREAD

**Issue by tgibson11** [icefields/Power-Ampache-2#119]
Basically what the title says.

I have a very long, not-human-friendly server URL, that I have no desire to type in manually. But there appears to be no way to paste text into any of the fields on the initial login screen.

**Comment by icefields** [comment]
Sounds odd, that's exactly how I login when I test the app. Anyway, I can make it explicit for the text fields to allow copy paste, easy enough to have it ready for the next release. Which is probably going to be on Monday/Tuesday for the Github release, FDroid takes 3 to 6 extra days. Thanks for reporting.

**Comment by tgibson11** [comment]
Thanks!

That is strange that it would work for you but not for me. I get the haptic feedback when I press & hold in one of the text fields, but the copy/paste menu doesn't appear.  Every other app seems to be working fine for me.

**Comment by TaKouMyS** [comment]
Hey, 
Just to let you know that I have the same issue!

Have a nice day

**Comment by icefields** [comment]
> Hey, Just to let you know that I have the same issue!
> 
> Have a nice day

ok, sounds annoying :( . It will be definitely fixed in the next release (`1.00-57`), which will be on Github around Monday or Tuesday, and on FDroid by the end of next week.

in the meantime:
if you use any password manager keyboard, like keepassDX (I think the feature is called MagicKeyboard), you can make the keyboard copy your credentials automatically.

**Comment by icefields** [comment]
found the issue, it's problem with the android Modal Bottom Sheet, doesn't happen on all phones: https://issuetracker.google.com/issues/327085717?pli=1
<br>
I will switch to dialogs instead of bottom sheets until google fixes this, I already tested and it works. 
The new version with the fix will be up tonight or tomorrow morning. 3 to 6 days for FDroid.

**Comment by icefields** [comment]
The issue seems to be solved, starting version 1.00-57 , I'm going to close this thread.
Current Github Release is 1.00-58 . That one has the fix already since 2 versions.
Fdroid is behind, currently version 1.00-55, I expect 1.00-56 to be published around today or tomorrow, 1.00-57 by end of the week, 1.00-58 next week.

**Comment by icefields** [comment]
The issue seems to be solved, starting version 1.00-57 . I'm going to close this thread.
Current Github Release is 1.00-58 . It has the fix already, since 2 versions.
Fdroid is behind, currently version 1.00-55 . I expect 1.00-56 to be published around today or tomorrow, 1.00-57 by end of the week, 1.00-58 next week.
