### ISSUE TITLE
On Download, serialized data passed to the Worker exceedes the max size allowed (Solution: only pass songId instead of full object)

### ISSUE THREAD

**Issue by lachlan-00** [icefields/Power-Ampache-2#24]
I think this one would be limiting the length of the url. Which is good because 3300 song ids would definitely be too long to send

![Screenshot_20240131_171322_ConnectBot.jpg](https://github.com/icefields/Power-Ampache-2/assets/1305249/2fbd6a30-3d73-4b9a-b4ed-c4eb08b38867)

**Comment by icefields** [comment]
Beside the steps, I also need to know what happens next.
Does the app crash? Does it skip one download and finished the others or the download process is completely stopped? I created a playlist of 41k songs and started downloading, I didn't experience this bug (so far, still downloading), any help fixing this issue is appreciated.

**Comment by lachlan-00** [comment]
Looks fixed from 0.08 onwards

**Comment by icefields** [comment]
I'm going to reopen this, from the crash trace I received yesterday night looks like it's still happening silently and that's what causing issues with downloads, at least from what I see in the logs.
Anyway, the bug is not with the url, it's with the serialized "Song" object I pass from the download-worker to the main thread, apparently some times that object exceeds the max size allowed for passing object between threads. 
I will implement a fix today, I'm going to pass the songId only instead of the full object, the worker can then retrieve the song object by itself instead of passing big serialized objects around.

`"java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized\n\tat androidx.work.Data.toByteArrayInternal(Data.java:404)\n\tat androidx.work.Data$Builder.build(Data.java:941)\n\tat androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.kt:32)\n\tat androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:224)\n\tat androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:144)\n\tat androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)\n\tat java.lang.Thread.run(Thread.java:1012)\n"`

<br><br>

**Comment by lachlan-00** [comment]
I see downloads are not crashing the app but some songs will not download and stop the process.

I've tested a few times on my lists. 4-8 songs usually and then a stop. Could that error be a cause too?

Will this error show up on Android studio if i load in there?

**Comment by icefields** [comment]
That issue should have been fixed on 0.10-beta. If you're on that version then the problem doesn't seem to be solved, and I'll look into it again.
Make sure you're on 0.10-beta , the other day I released 3 versions in a day, very easy lo lose track.

The log won't who show if you connect to android studio because the exception is caught without outputting any log on production releases. But you could go to Settings and enable remote logging and I will get a log of the exception.

**Comment by lachlan-00** [comment]
cool, i've done that, that will save me having to ask a lot more questions
